---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/7/30 10:28
---

local reg_mgr = {}

---获取manifest信息
function res_mgr:get_manifest()
    return gCSharp.GetManifest()
end

---获取版本号
function res_mgr:get_version_str()
    return gCSharp.GetVersionStr();
end

---同步加载资源
function res_mgr:load(eres,module,asset_name)
    return gCSharp.Load(eres,module,asset_name)
end

---异步加载资源
function res_mgr:load_async(eres,module,asset_name,callback)
    return gCSharp.LoadAsync(eres,module,asset_name,callback)
end

---加载manifest
function res_mgr:load_manifest()
    gCSharp.LoadManifest()
end

---清理预加载的prefab
function res_mgr:clear_pre_go_cache()
    gCSharp.ClearPreGoCache()
end


return res_mgr