---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/8/15 18:31
---

local appCfg = {}

--- 包体键名 用于映射服务器
appCfg.packKey = ""

--- 系统枚举
appCfg.eOs = {
    win = 2,
    ios = 8,
    android = 11,
}

--- 系统
appCfg.os = appCfg.eOs.win

--- 版本枚举
appCfg.enum = {
    develop = "develop",
    release = "release",
}

--- 当前版本
appCfg.currTarget = appCfg.enum.develop

--- 版本对应配置
appCfg.cfgs = {
    -- 开发版
    [appCfg.enum.develop] = {
        -- 资源服host和port 由c#端传入
        resHost = "", --"http://localhost:%s/PackTest01/StandaloneWindows64/%s",
        resPort = 80,
        -- 登录服务器
        loginServer = "http://192.168.0.118:8888/?type=login&name=%s&password=%s",
        -- 获取服务器列表
        getServer = "http://192.168.0.118:8888/?type=getversion&version=%s&username=%s&time=%s",
        -- 注册
        registerServer = "http://192.168.0.118:8888/?type=register&name=%s&password=%s",
        -- 获取角色服务器
        roleServer = "http://192.168.0.118:8888/role?cmd=get&token=%s&time=%s",
        -- 是否开启引导
        guide = false,
        -- 是否开启作弊
        cheat = false,
        -- 渠道号
        channelId = 1,
        -- 子渠道号
        subChannelId = 1,
    }
}

--- 运行模式枚举
appCfg.eRunMode =
{
    editorMode = 0,
    localMode = 1,
    packageMode = 2,
}

--- 运行模式 从C#读取
appCfg.runMode = nil

--- 版本 从C#读取
appCfg.version = nil

--- ==================== 公共方法 ====================

--- 获得当前版本的配置信息
function appCfg.get_cfg()
    return appCfg.cfgs[appCfg.currTarget]
end

--- 更新配置 有新的则用新的，没则用原来的
function appCfg.update_cfg(newCfg)
    if not newCfg then
        return
    end

    -- 获得原配置
    local cfg = appCfg.get_cfg()

    -- 遍历新的表
    for k, v in pairs(newCfg) do
        -- 替换原表
        cfg[k] = v
    end
end

--- 检测是否是该版本
---@param target: 检测目标 app_cfg.enum类型
function appCfg.check(target)
    return appCfg.currTarget == target
end

--- 设置运行模式
---@param runModeVal: 运行模式枚举对应数字
function appCfg.set_run_mode(runModeVal)
    for i, v in pairs(appCfg.eRunMode) do
        if v == runModeVal then
            appCfg.runMode = v
            return
        end
    end
end

return appCfg