---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/13 11:38
---

local dataCenter = {
    player = require("modules/data_center/player_data"):new(),
    bag = require("modules/data_center/bag_data"):new(),
    hero = require("modules/data_center/hero_data"):new(),
    master = require("modules/data_center/master_data"):new(),
    audio = require("modules/data_center/audio_data"):new(),
    world = require("modules/data_center/world_data"):new(),
}

--- 设置网络
function dataCenter.set_net(listNet)
    listNet = listNet or {}

    for i, v in pairs(listNet) do
        v.ptcIns:Reg("dataCenter", v.callback, v.errorCallback)
    end
end

--- 取消网络
function dataCenter.clear_net(listNet)
    listNet = listNet or {}

    for i, v in pairs(listNet) do
        v.ptcIns:UnReg("dataCenter")
    end
end

--- 初始化数据
function dataCenter.init()
    for i, v in pairs(dataCenter) do
        if type(v) ~= "function" then
            v:OnInit()
            dataCenter.set_net(v:OnSetNet())
        end
    end
end

--- 清空数据
function dataCenter.clear()
    for i, v in pairs(dataCenter) do
        if type(v) ~= "function" then
            v:OnClear()
            dataCenter.clear_net(v:OnSetNet())
        end
    end
end

return dataCenter