---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/8/13 13:10
---

local helper = {}

--- 是否是空物体节点
function helper.is_nil(obj)
    return obj == nil or obj:Equals(nil)
end

--- 值转尺寸字符串
function helper.value_2_size_str(value)
    local array = {"B", "KB", "MB", "GB", "TB"}

    local uVal = 1

    -- 反向遍历
    for i = #array, 1, -1 do
        -- 计算阶段值
        uVal = 1024 ^ (i - 1)

        -- 是否大于等于阶段值
        if value >= uVal then
            return string.format("%.2f", value / uVal) .. array[i]
        end
    end

    return value .. array[1]
end



--- 强制刷新UI
---@param rectTrans: 节点
---@param isGetComp: 是否还需要获取一次组件(*)
function helper.refresh_ui(rectTrans, isGetComp)
    local comp = rectTrans

    -- 是否还需要获取一次组件
    if isGetComp then
        comp = rectTrans:GetComponent("RectTransform")
    end

    gUnity.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(comp)
end

--- 遍历子节点
---@param node: 节点
---@param callback: 回调方法 传递子节点(Transform类型) 和 下标(1开始)
---@param isForwardPair: 是否正向遍历(*) 默认正向
function helper.pair_child_node(node, callback, isForwardPair)
    if isForwardPair == nil then
        isForwardPair = true
    end

    local startIdx = 0
    local endIdx = node.childCount - 1
    local dir = 1

    -- 是否反向
    if not isForwardPair then
        startIdx = endIdx
        endIdx = 0
        dir = -1
    end

    -- 遍历
    for i = startIdx, endIdx, dir do
        local t = i + 1
        callback(node:GetChild(i), t)
    end
end

--- 销毁子节点
---@param node: 节点
---@param isRecycle: 是否回收
function helper.destroy_children(node, isRecycle)
    helper.pair_child_node(node, function (cell)
        helper.destroy_node(cell, isRecycle)
    end, false)
end

return helper