---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/8/13 13:51
---

local log = {
}

--- 打印
---@param content : 内容
function log.print(content)
    if type(content) == "table" then
        print(log.get_table_str(content))
    else
        print(string.format("%s\n%s", content, debug.traceback()))
    end
end

function log.get_table_str(t)
    local str = ""
    for k,v in pairs(t) do
        if type(v) == "table" then
            str = string.format("%s %s = {%s},",str,tostring(k),log.get_table_str(v))
        else
            str = string.format("%s %s = %s,",str,tostring(k),tostring(v))
        end
    end
    return str
end

--- 打印一组数据
---@param ... : 内容组
function log.print_group(...)
    local array = {}
    for i, v in pairs({ ... }) do
        table.insert(array,tostring(v))
    end
    print(string.format("%s\n%s", table.concat(array, " "), debug.traceback()))
end

--- 打印错误
---@param content : 内容
function log.print_error(content)
    error(content)
end

return log