---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/8/13 13:51
---

local log = {
}

--- 打印
---@param content : 内容
function log.print(content)
    print(string.format("%s\n%s", content, debug.traceback()))
end

--- 打印一组数据
---@param ... : 内容组
function log.print_group(...)
    local array = {}
    for i, v in pairs({ ... }) do
        table.insert(array, tostring(v))
    end
    print(string.format("%s\n%s", table.concat(array, " "), debug.traceback()))
end

--- 打印错误
---@param content : 内容
function log.print_error(content)
    error(content)
end

return log