---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/7/29 17:43
---

local mgrs = {}

mgrs.ui = require('mgrs/ui_new/ui_mgr')
mgrs.res = require('mgrs/res/res_mgr')
--mgrs.update = require('mgrs/update/update_mgr')
--mgrs.net = require('mgrs/net/net_mgr')
--mgrs.cover = require('mgrs/cover/cover_mgr')
mgrs.timer = require("mgrs/timer/timer_mgr") --#
mgrs.msg = require("mgrs/msg/msg_mgr") --#
mgrs.scene = require("mgrs/scene/scene_mgr") -- #
mgrs.unityUpdate = require("mgrs/unity_update/unity_update_mgr") -- #
mgrs.pool = require("mgrs/pool/pool_mgr") -- +

return mgrs