---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/16 18:09
---

local unityUpdateMgr = {
    isInit = false,
    listUpdate = {},
    listFixedUpdate = {},
    listLateUpdate = {},
}

--- 初始化
function unityUpdateMgr.init()
    if unityUpdateMgr.isInit then
        return
    end

    -- 标记初始化
    unityUpdateMgr.isInit = true

    -- 注册
    gCSharp.RegUpdate(unityUpdateMgr.on_update)
    gCSharp.RegLateUpdate(unityUpdateMgr.on_late_update)
    gCSharp.RegFixedUpdate(unityUpdateMgr.on_fixed_update)
end

--- 销毁回调
function unityUpdateMgr.on_destroy()
    gCSharp.UnRegUpdate(unityUpdateMgr.on_update)
    gCSharp.UnRegLateUpdate(unityUpdateMgr.on_late_update)
    gCSharp.UnRegFixedUpdate(unityUpdateMgr.on_fixed_update)
end

--- Update回调
function unityUpdateMgr.on_update()
    -- 遍历
    for i, v in pairs(unityUpdateMgr.listUpdate) do
        v()
    end
end

--- LateUpdate回调
function unityUpdateMgr.on_late_update()
    -- 遍历
    for i, v in pairs(unityUpdateMgr.listLateUpdate) do
        v()
    end
end

--- FixedUpdate回调
function unityUpdateMgr.on_fixed_update()
    -- 遍历
    for i, v in pairs(unityUpdateMgr.listFixedUpdate) do
        v()
    end
end

--- 注册Update
function unityUpdateMgr.reg_update(callback)
    unityUpdateMgr.listUpdate[tostring(callback)] = callback
end

--- 注销Update
function unityUpdateMgr.unreg_update(callback)
    unityUpdateMgr.listUpdate[tostring(callback)] = nil
end

--- 清除Update
function unityUpdateMgr.clear_update()
    unityUpdateMgr.listUpdate = {}
end

--- 注册LateUpdate
function unityUpdateMgr.reg_lateupdate(callback)
    unityUpdateMgr.listLateUpdate[tostring(callback)] = callback
end

--- 注销LateUpdate
function unityUpdateMgr.unreg_lateupdate(callback)
    unityUpdateMgr.listLateUpdate[tostring(callback)] = nil
end

--- 清除LateUpdate
function unityUpdateMgr.clear_lateupdate()
    unityUpdateMgr.listLateUpdate = {}
end

--- 注册FixedUpdate
function unityUpdateMgr.reg_fixedupdate(callback)
    unityUpdateMgr.listFixedUpdate[tostring(callback)] = callback
end

--- 注销FixedUpdate
function unityUpdateMgr.unreg_fixedupdate(callback)
    unityUpdateMgr.listFixedUpdate[tostring(callback)] = nil
end

--- 清除FixedUpdate
function unityUpdateMgr.clear_fixedupdate()
    unityUpdateMgr.listFixedUpdate = {}
end

return unityUpdateMgr