---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/26 9:31
---

--- 限制数值
--- @param numValue: 待限制的数值
--- @param minValue: 最小数值
--- @param maxValue: 最大数值
function math.clamp(numValue, minValue, maxValue)
    if numValue < minValue then
        return minValue
    end
    if (numValue > maxValue) then
        return maxValue
    end
    return numValue
end

--- 限制数值到0~1
--- @param numValue: 待限制的数值
function math.clamp01(numValue)
    return math.clamp(numValue, 0, 1)
end