---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/26 9:29
---

--- 分割字符串
---@param str：原字符串
---@param splitStr: 分隔符
---@return: 分割后的字符串数组
function string.split(str, splitStr)
    -- 没有该分隔符
    if string.find(str, splitStr) == nil then
        return { str }
    end

    local result = {}

    -- 拼接正则
    local pat = string.format("([^%s]+)", splitStr)

    -- 正则判断
    local pairFunc = string.gmatch(str, pat)

    -- 遍历所有值
    for val in pairFunc do
        -- 添加到列表
        table.insert(result, val)
    end

    return result
end

--- 字符串是否空
function string.is_nil(str)
    return str == nil or str == ""
end

return string