---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/10 16:08
---

local baseScene = gClass.declare("baseScene")

--- ==================== 生命周期 ====================

--- 构造方法
function baseScene:Ctor()

end

--- ==================== 生命周期 ====================

--- 初始化回调
function baseScene:OnInit()
    -- 初始化数据
    self.sceneKey = nil             -- 场景枚举
    self.sceneArgs = {}             -- 参数
    self.isSceneLoading = true      -- 标记是否在加载中
    self.isSceneUnloading = false   -- 标记是否在卸载中
end

--- 加载完毕回调
function baseScene:OnLoaded()

end

--- 关闭前回调
function baseScene:OnClose()

end

return baseScene