---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/10 12:08
---

local sceneCfg = {
    --- 场景枚举
    eScene = {
        main = "Main",
        world = "World",
    },
}

--- 配置
sceneCfg.cfg = {
    [sceneCfg.eScene.main] = {
        module = "MainCity",
        name = "MainScene",
        isClearOthers = true,      -- 是否清除其他的场景(即清除栈)
        getIns = function()
            return require("modules/scenes/main_scene"):new()
        end,
    },
    [sceneCfg.eScene.world] = {
        module = "World",
        name = "WorldScene",
        isClearOthers = true,      -- 是否清除其他的场景(即清除栈)
        getIns = function()
            return require("modules/scenes/world_scene"):new()
        end,
    },
}

return sceneCfg