---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/10 12:08
---

local scene1 = require("scene1")
local scene2 = require("scene2")




--- 配置
local scene_config = {
    [gSceneKey.SCENE1] = {
        module = "mode1", --模块名
        name = "Scene1", --场景名
        scene_class = scene1, --场景对象
        isloading = true, --是否使用loading 场景
        allow_pop = false, -- 是否允许pop该场景
        reload_ui = true,--是否从新加载UI
    },
    [gSceneKey.SCENE2] = {
        module = "mode2",
        name = "Scene2",
        scene_class = scene2,
        isloading = true,
        allow_pop = true,
        reload_ui = true,
    },
}

return scene_config