---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/3 11:17
---

local coverCfg = {}

--- 遮罩枚举
coverCfg.eCover = {
    uiLoading = "UILoadingCover",   -- ui加载用顶层遮罩
    net = "NetCover",               -- 网络请求
    tcp = "TcpCover",               -- tcp网络请求
    sceneLoading = "SceneLoadingCover"   -- 场景加载遮罩
}

--- 遮罩额外子物体
coverCfg.exChild = {
    -- 网络请求增加连接效果
    [coverCfg.eCover.net] = {
        showDelay = 2,                      -- 显示延迟时间 s
        module = "base",                    -- 模块名
        assetName = "NetCoverAnim.prefab",  -- 资源名
        isAsync = true,                     -- 异步加载
        callback = nil,                     -- 显示回调 传回1个参数 trans:额外资源节点
    },
    -- tcp网络请求连接效果
    [coverCfg.eCover.tcp] = {
        showDelay = 2,                      -- 显示延迟时间 s
        module = "base",                    -- 模块名
        assetName = "NetCoverAnim.prefab",  -- 资源名
        isAsync = true,                     -- 异步加载
        callback = nil,                     -- 显示回调 传回1个参数 trans:额外资源节点
    },
    -- 场景加载进度
    [coverCfg.eCover.sceneLoading] = {
        module = "SceneLoading",
        assetName = "SceneLoading.prefab",
        isAsync = false,
        callback = function (trans, isShow)
            -- 获得背景
            local bg = trans:Find("ImgBG"):GetComponent("Image")

            -- 获得进度条
            local slider = trans:Find("ImgBottom/Slider"):GetComponent("Slider")

            -- 是否显示
            if isShow then
                -- 设置进度条
                slider.value = 0

                -- 设置背景
                local imgName = string.format("nfs_loading_beijing_%s.png", math.random(1, 11))
                bg.sprite = gMgrs.res.load_sprite("SceneLoading", imgName)

                -- 注册消息
                gMgrs.msg.reg(gMgrs.msg.eMsg.sceneLoading, "progress", function (progress)
                    -- 设置进度条显示
                    slider.value = progress
                end, "1")

            else    -- 隐藏
                -- 设置进度条
                slider.value = 1

                -- 注销消息
                gMgrs.msg.un_reg(gMgrs.msg.eMsg.sceneLoading, "progress", "1")
            end
        end,
    },
}

return coverCfg