---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LeeroyLin.
--- DateTime: 2021/9/24 12:28
---

local pool_mgr = {}

--- 尝试获得资源
---@param key: 键名
function pool_mgr.try_get(key)
    return gCSharp.TryGet(key)
end

--- 通过模块名和资源名尝试获得资源
---@param module: 模块名
---@param assetName: 资源名
function pool_mgr.try_get_asset(module, assetName)
    return gCSharp.TryGetAsset(module, assetName)
end

--- 通过模块名和资源名获得键
---@param module: 模块名
---@param assetName: 资源名
function pool_mgr.get_key(module, assetName)
    return module.."#"..assetName
end

--- 回收
---@param trans: 节点
---@param customKey: 自定义键
function pool_mgr.recycle(trans, customKey)
    gCSharp.Recycle(trans, customKey)
end

--- 设置容量
---@param key: 键名
---@param capacity: 容量
function pool_mgr.set_capacity(key, capacity)
    gCSharp.SetCapacity(key, capacity)
end

--- 通过模块名和资源名设置容量
---@param module: 模块名
---@param assetName: 资源名
---@param capacity: 容量
function pool_mgr.set_asset_capacity(module, assetName, capacity)
    gCSharp.SetAssetCapacity(module, assetName, capacity)
end

--- 清空对应键的对象池
---@param key: 键名
function pool_mgr.clear(key)
    gCSharp.Clear(key)
end

--- 清空对应资源的对象池
---@param module: 模块名
---@param assetName: 资源名
function pool_mgr.clear_asset(module, assetName)
    gCSharp.ClearAsset(module, assetName)
end

--- 清除全部的对象池
function pool_mgr.clear_all()
    gCSharp.ClearAll()
end

return pool_mgr